version: "3.9"
volumes:
  mysql_main_data:
  mysql_sub_data:
services:
  db_main:
    image: mysql:8
    container_name: "${APP_NAME}_db_main"
    environment:
      MYSQL_DATABASE: "${APP_NAME}_main_${RAILS_ENV:-development}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql/conf/my_main.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_main_data:/var/lib/mysql
    ports:
      - "${DB_MAIN_PORT:-3306}:3306"
  db_sub:
    image: mysql:8
    container_name: "${APP_NAME}_db_sub"
    environment:
      MYSQL_DATABASE: "${APP_NAME}_sub_${RAILS_ENV:-development}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql/conf/my_sub.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_sub_data:/var/lib/mysql
    ports:
      - "${DB_SUB_PORT:-3307}:3306"

  app:
    build:
      context: .
      args:
        - "APP_NAME=${APP_NAME}"
        - "WORKDIR=/${APP_NAME}"
        - "USER=${APP_USER:-${USER}}"
        - "USER_ID=${APP_USER_ID:-0}"
        - "GROUP=${APP_GROUP:-${USER}}"
        - "GROUP_ID=${APP_GROUP_ID:-0}"
    user: "${APP_USER_ID:-0}:${APP_GROUP_ID:-0}"
    container_name: "${APP_NAME}_app"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: "${RAILS_ENV:-development}"
    volumes:
      - ".:/${APP_NAME}"
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      - db_main
      - db_sub

  redis:
     image: redis
     command: redis-server
